version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nectal_web
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nectal.com:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    container_name: nectal_php
    volumes:
      - ../nectal.com/:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: nectal_db
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nectal_phpmyadmin
    ports:
      - 8888:80
    depends_on:
      - db
